#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

LEN=$(cat .git/COMMIT_EDITMSG | egrep -v "^#|^$" | sed 's/ *$//g' | wc -m)
if [[ "$LEN" -eq 0 ]]; then
  exec < /dev/tty && node_modules/.bin/cz --hook || true
fi
